
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class GUI extends javax.swing.JFrame {

    private DefaultTableModel model = new DefaultTableModel();
    private int RowSize=0;
    private int language=0;
    private String fun_name,class_name,arg_list="",return_type;
    private DefaultCode defaultcode;
    private List<List<List<String>> > C_list=new ArrayList<List<List<String>>>();
    private List<List<List<String>> > Cpp_list=new ArrayList<List<List<String>>>();
    private List<List<List<String>> > Java_list=new ArrayList<List<List<String>>>();
    
    
    /** Creates new form GUI */
    public GUI() {
        initComponents();
        Initialise();
        
    }
    
    private void Initialise()
    {
        //As Default Language is C
        classlable.setVisible(false);
        classfield.setVisible(false);
        
        model=(DefaultTableModel) jTable1.getModel();
        //Create list of element for input argument
        createlist();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        langbox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        funfield = new javax.swing.JTextField();
        classlable = new javax.swing.JLabel();
        classfield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        returnfield = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CodeArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        resetbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("Language");

        langbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "C", "C++", "Java" }));
        langbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                langboxActionPerformed(evt);
            }
        });

        jLabel2.setText("Function Name");

        classlable.setText("Class Name");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Variable Datatype", "Variable Name", "Dimension", "Size1", "Size2"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Add Variable");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remove Variable");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Return Type");

        jButton3.setText("Generate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        CodeArea.setColumns(20);
        CodeArea.setRows(5);
        jScrollPane2.setViewportView(CodeArea);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel4.setText("Generated Code");

        resetbutton.setText("Reset");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(resetbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(langbox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(funfield, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(classlable, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(classfield, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(returnfield, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(langbox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(funfield, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classfield, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classlable, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(returnfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3))))
                    .addComponent(resetbutton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void langboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_langboxActionPerformed
        // TODO add your handling code here:
        language=langbox.getSelectedIndex();
        if(language==0||language==1)
        {
            classlable.setVisible(false);
            classfield.setVisible(false);
        }
        else 
        {
            classlable.setVisible(true);
            classfield.setVisible(true);
        }
    }//GEN-LAST:event_langboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RowSize++;
        model.insertRow(RowSize, new Object[]{});
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        model.removeRow(RowSize--);
        RowSize=Math.max(RowSize,-1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        fun_name=funfield.getText();
        class_name=classfield.getText();
        return_type=returnfield.getText();
        Showsuggestion();
        defaultcode=new DefaultCode(fun_name,class_name,return_type);
        GenerateCode();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_resetbuttonActionPerformed

    private void reset()
    {
        funfield.setText("");
        classfield.setText("");
        returnfield.setText("");
        for(int i=0;i<= RowSize;i++)
            model.removeRow(0);
        RowSize=-1;
        fun_name="";
        class_name="";
        return_type="";
        arg_list="";
        CodeArea.setText("");
    }
    private void GenerateCode()
    {
        String generatedcode;
        if(language==0)
        {
            generatedcode=defaultcode.generatecode_c(arg_list);
        }
        else if(language==1)
        {
            generatedcode=defaultcode.generatecode_cpp(arg_list);
        }
        else
        {
            generatedcode=defaultcode.generatecode_java(arg_list);
        }
        CodeArea.setText(generatedcode);
    }
    private void Showsuggestion()
    {
        
        for(int i=0;i<=RowSize;i++)
        {
            int dim=Integer.parseInt((String)model.getValueAt(i, 2));
            ArrayList<String> suggest=new ArrayList<String>();
            int cnt=1;
            switch(dim)
            {
                case 0:
                        suggest.add((String)model.getValueAt(i, 0)+C_list.get(dim).get(0).get(0)+(String)model.getValueAt(i, 1));
                    break;
                case 1:
                    if(language==0)
                    {
                        suggest.add((String)model.getValueAt(i, 0)+C_list.get(dim).get(0).get(0)+(String)model.getValueAt(i, 1));
                        suggest.add((String)model.getValueAt(i, 0)+" "+(String)model.getValueAt(i, 1)+C_list.get(dim).get(1).get(0));
                    }
                    else if(language==1)
                    {
                        suggest.add((String)model.getValueAt(i, 0)+Cpp_list.get(dim).get(0).get(0)+(String)model.getValueAt(i, 1));
                        suggest.add((String)model.getValueAt(i, 0)+" "+(String)model.getValueAt(i, 1)+Cpp_list.get(dim).get(1).get(0));
                        suggest.add(Cpp_list.get(dim).get(2).get(0) +(String)model.getValueAt(i, 0)+Cpp_list.get(dim).get(2).get(1) +" "+(String)model.getValueAt(i, 1));
                    }
                    else
                    {
                        suggest.add((String)model.getValueAt(i, 0)+Java_list.get(dim).get(0).get(0) +(String)model.getValueAt(i, 1));
                        suggest.add(Java_list.get(dim).get(1).get(0) +(String)model.getValueAt(i, 0)+Java_list.get(dim).get(1).get(1) +" "+(String)model.getValueAt(i, 1));
                    }
                    break;
                case 2:
                    if(language==0)
                    {
                        suggest.add((String)model.getValueAt(i, 0)+" "+(String)model.getValueAt(i, 1)+C_list.get(dim).get(0).get(0) +(String)model.getValueAt(i, 4)+C_list.get(dim).get(0).get(1));
                    }
                    else if(language==1)
                    {
                        
                        suggest.add((String)model.getValueAt(i, 0)+" "+(String)model.getValueAt(i, 1)+Cpp_list.get(dim).get(0).get(0) +(String)model.getValueAt(i, 4)+Cpp_list.get(dim).get(0).get(1));
                        suggest.add(Cpp_list.get(dim).get(1).get(0) +(String)model.getValueAt(i, 0)+Cpp_list.get(dim).get(1).get(1) +" "+(String)model.getValueAt(i, 1));
                    }
                    else
                    {
                        
                        suggest.add((String)model.getValueAt(i, 0)+" "+(String)model.getValueAt(i, 1)+Java_list.get(dim).get(0).get(0));
                        suggest.add(Java_list.get(dim).get(1).get(0) +(String)model.getValueAt(i, 0)+Java_list.get(dim).get(1).get(1) +" "+(String)model.getValueAt(i, 1));
                    }
            }
            String message="Suggetions for argument "+String.valueOf(i+1)+"\n";
            for(String s: suggest)
            {
                message+=String.valueOf(cnt++)+") "+s+"\n";
            }
            String input=JOptionPane.showInputDialog(message);
            int option=Integer.parseInt(input);
            arg_list+=suggest.get(option-1);
            if(i<RowSize)
                arg_list+=",";
        }
    }
    private void createlist()
    {
        //create list of C elements
        //Add dimension 0 element
        C_list.add(new ArrayList<List<String>>());
        C_list.get(0).add(new ArrayList<String>());
        C_list.get(0).get(0).add(" ");
        //Add dimension 1 element
        C_list.add(new ArrayList<List<String>>());
        C_list.get(1).add(new ArrayList<String>());
        C_list.get(1).get(0).add("* ");
        C_list.get(1).add(new ArrayList<String>());
        C_list.get(1).get(1).add("[]");
        //Add dimension 2 element
        C_list.add(new ArrayList<List<String>>());
        C_list.get(2).add(new ArrayList<String>());
        C_list.get(2).get(0).add("[][");
        C_list.get(2).get(0).add("]");
        
        //create list of Cpp elements
        //Add dimension 0 element
        Cpp_list.add(new ArrayList<List<String>>());
        Cpp_list.get(0).add(new ArrayList<String>());
        Cpp_list.get(0).get(0).add(" ");
        //Add dimension 1 element
        Cpp_list.add(new ArrayList<List<String>>());
        Cpp_list.get(1).add(new ArrayList<String>());
        Cpp_list.get(1).get(0).add("* ");
        Cpp_list.get(1).add(new ArrayList<String>());
        Cpp_list.get(1).get(1).add("[]");
        Cpp_list.get(1).add(new ArrayList<String>());
        Cpp_list.get(1).get(2).add("vector<");
        Cpp_list.get(1).get(2).add(">");
        //Add dimension 2 element
        Cpp_list.add(new ArrayList<List<String>>());
        Cpp_list.get(2).add(new ArrayList<String>());
        Cpp_list.get(2).get(0).add("[][");
        Cpp_list.get(2).get(0).add("]");
        Cpp_list.get(2).add(new ArrayList<String>());
        Cpp_list.get(2).get(1).add("vector<vector<");
        Cpp_list.get(2).get(1).add("> >");
        
        
        
        //create list of Java elements
        //Add dimension 0 element
        Java_list.add(new ArrayList<List<String>>());
        Java_list.get(0).add(new ArrayList<String>());
        Java_list.get(0).get(0).add(" ");
        //Add dimension 1 element
        Java_list.add(new ArrayList<List<String>>());
        Java_list.get(1).add(new ArrayList<String>());
        Java_list.get(1).get(0).add("[]");
        Java_list.get(1).add(new ArrayList<String>());
        Java_list.get(1).get(1).add("ArrayList<");
        Java_list.get(1).get(1).add(">");
        //Add dimension 2 element
        Java_list.add(new ArrayList<List<String>>());
        Java_list.get(2).add(new ArrayList<String>());
        Java_list.get(2).get(0).add("[][]");
        Java_list.get(2).add(new ArrayList<String>());
        Java_list.get(2).get(1).add("ArrayList<ArrayList<");
        Java_list.get(2).get(1).add("> >");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CodeArea;
    private javax.swing.JTextField classfield;
    private javax.swing.JLabel classlable;
    private javax.swing.JTextField funfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox langbox;
    private javax.swing.JButton resetbutton;
    private javax.swing.JTextField returnfield;
    // End of variables declaration//GEN-END:variables
}
